from typing import List, Tuple

# Format: (title, artist, year, [genres])
music_db: List[Tuple[str, str, int, List[str]]] = [
    ("Imagine", "John Lennon", 1971, ["Soft Rock"]),
    ("Billie Jean", "Michael Jackson", 1983, ["Pop", "R&B"]),
    ("Smells Like Teen Spirit", "Nirvana", 1991, ["Grunge", "Rock"]),
    ("Come As You Are", "Nirvana", 1992, ["Grunge", "Rock"]),
    ("Heart-Shaped Box", "Nirvana", 1993, ["Grunge", "Rock"]),
    ("Lithium", "Nirvana", 1991, ["Grunge", "Rock"]),
    ("Like a Rolling Stone", "Bob Dylan", 1965, ["Folk Rock"]),
    ("Bohemian Rhapsody", "Queen", 1975, ["Rock"]),
    ("Shape of You", "Ed Sheeran", 2017, ["Pop"]),
    ("Hey Jude", "The Beatles", 1968, ["Rock"]),
    ("Hotel California", "Eagles", 1977, ["Rock"]),
    ("Sweet Child O' Mine", "Guns N' Roses", 1987, ["Hard Rock"]),
    ("Stayin' Alive", "Bee Gees", 1977, ["Disco", "Pop"]),
    ("Don't Stop Believin'", "Journey", 1981, ["Rock"]),
    ("Superstition", "Stevie Wonder", 1972, ["Funk", "Soul"]),
    ("Uptown Funk", "Mark Ronson ft. Bruno Mars", 2014, ["Funk", "Pop"]),
    ("Rolling in the Deep", "Adele", 2010, ["Pop", "Soul"]),
    ("Lose Yourself", "Eminem", 2002, ["Hip Hop"]),
    ("Nikes on My Feet", "Mac Miller", 2010, ["Hip Hop"]),
    ("Self Care", "Mac Miller", 2018, ["Hip Hop"]),
    ("The Spins", "Mac Miller", 2010, ["Hip Hop"]),
    ("Good News", "Mac Miller", 2020, ["Hip Hop"]),
    ("Ladders", "Mac Miller", 2018, ["Hip Hop"]),
    ("Praise The Lord (Da Shine)", "A$AP Rocky", 2018, ["Hip Hop"]),
    ("L$D", "A$AP Rocky", 2015, ["Hip Hop", "Psychedelic"]),
    ("Peso", "A$AP Rocky", 2011, ["Hip Hop"]),
    ("Goldie", "A$AP Rocky", 2012, ["Hip Hop"]),
    ("Empire State of Mind", "Jay-Z ft. Alicia Keys", 2009, ["Hip Hop", "Pop"]),
    ("Mr. Brightside", "The Killers", 2003, ["Rock"]),
    ("Viva La Vida", "Coldplay", 2008, ["Pop", "Rock"]),
    ("Wonderwall", "Oasis", 1995, ["Rock"]),
    ("Dreams", "Fleetwood Mac", 1977, ["Rock"]),
    ("Go Your Own Way", "Fleetwood Mac", 1977, ["Rock"]),
    ("Africa", "Toto", 1982, ["Rock"]),
    ("September", "Earth, Wind & Fire", 1978, ["Funk", "Soul"]),
    ("Thriller", "Michael Jackson", 1982, ["Pop", "Rock"]),
    ("Beat It", "Michael Jackson", 1982, ["Pop", "Rock"]),
    ("Purple Rain", "Prince", 1984, ["Pop", "Rock"]),
    ("Every Breath You Take", "The Police", 1983, ["Rock"]),
    ("Radioactive", "Imagine Dragons", 2012, ["Rock"]),
    ("Clocks", "Coldplay", 2002, ["Pop", "Rock"]),
]
